name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APKs for all ABIs
      run: ./gradlew assembleDebug

    - name: List APKs
      run: ls app/build/outputs/apk/debug/

    - name: Get version name
      id: get_version
      run: |
        VERSION_NAME=$(grep versionName app/build.gradle.kts | head -1 | awk -F '"' '{print $2}')
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version_name }}
        name: Release v${{ steps.get_version.outputs.version_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload arm64-v8a APK to Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload armeabi-v7a APK to Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload x86 APK to Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-x86-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: app-arm64-v8a-debug-apk
        path: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

    - name: Upload armeabi-v7a APK
      uses: actions/upload-artifact@v4
      with:
        name: app-armeabi-v7a-debug-apk
        path: app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk

    - name: Upload x86 APK
      uses: actions/upload-artifact@v4
      with:
        name: app-x86-debug-apk
        path: app/build/outputs/apk/debug/app-x86-debug.apk

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

